src/Entity/Report.php
<?php

namespace App\Entity;

use App\Entity\Compagny\Compagny;
use App\Entity\Trainee\Trainee;
use App\Repository\ReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\ManyToOne(targetEntity=Compagny::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $company;

    /**
     * @ORM\ManyToOne(targetEntity=Trainee::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Trainee;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCompany(): ?Compagny
    {
        return $this->company;
    }

    public function setCompany(?Compagny $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getTrainee(): ?Trainee
    {
        return $this->Trainee;
    }

    public function setTrainee(?Trainee $Trainee): self
    {
        $this->Trainee = $Trainee;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }
}

templates/account.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	{{ encore_entry_link_tags('account') }}
{% endblock %}

{% block javascripts %}
	{{ encore_entry_script_tags('account') }}
{% endblock %}

{% block body %}

	<div class="container-fluid movable">

		<div class="sidebar">
			<div class="sidebar-logo">
				<a href="{{ path('account') }}">
					<i class="animate fas fa-arrow-left navbar-toogle"></i>
				</a>
				<a href="{{ path('app_home') }} ">
					<img src="{{ asset('images/pf.png') }}" alt="Logo">
				</a>
			</div>

			<ul>
				{% if not is_granted(constant('App\\Constants\\Permissions::ROLE_TRAINEE_NAME')) %}
					<li>
						<a href="{{ path('account') }}">
							<svg class="a_ ow ug" viewbox="0 0 24 24">
								<path class="pf ml" :class="page === 'dashboard' &amp;&amp; '!text-indigo-500'" d="M12 0C5.383 0 0 5.383 0 12s5.383 12 12 12 12-5.383 12-12S18.617 0 12 0z"></path>
								<path class="pf ma" :class="page === 'dashboard' &amp;&amp; 'text-indigo-600'" d="M12 3c-4.963 0-9 4.037-9 9s4.037 9 9 9 9-4.037 9-9-4.037-9-9-9z"></path>
								<path class="pf ml" :class="page === 'dashboard' &amp;&amp; 'text-indigo-200'" d="M12 15c-1.654 0-3-1.346-3-3 0-.462.113-.894.3-1.285L6 6l4.714 3.301A2.973 2.973 0 0112 9c1.654 0 3 1.346 3 3s-1.346 3-3 3z"></path>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.dashboard'|trans }}</span>
						</a>
					</li>
				{% endif %}
				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_ADMIN_NAME')) %}
					<li>
						<a href="{{ path('admin') }}">
							<svg
								xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512">
								<!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
								<path class="pf" d="M400 224h-24v-72C376 68.2 307.8 0 224 0S72 68.2 72 152v72H48c-26.5 0-48 21.5-48 48v192c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V272c0-26.5-21.5-48-48-48zm-104 0H152v-72c0-39.7 32.3-72 72-72s72 32.3 72 72v72z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.admin'|trans }}</span>
						</a>
					</li>
				{% endif %}
				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_SCHOOL_NAME')) %}
					<li>
						<a href="{{ path('app_degree_index') }}">
							<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 640 512">
								<path class="pf" d="M622.34 153.2L343.4 67.5c-15.2-4.67-31.6-4.67-46.79 0L17.66 153.2c-23.54 7.23-23.54 38.36 0 45.59l48.63 14.94c-10.67 13.19-17.23 29.28-17.88 46.9C38.78 266.15 32 276.11 32 288c0 10.78 5.68 19.85 13.86 25.65L20.33 428.53C18.11 438.52 25.71 448 35.94 448h56.11c10.24 0 17.84-9.48 15.62-19.47L82.14 313.65C90.32 307.85 96 298.78 96 288c0-11.57-6.47-21.25-15.66-26.87.76-15.02 8.44-28.3 20.69-36.72L296.6 284.5c9.06 2.78 26.44 6.25 46.79 0l278.95-85.7c23.55-7.24 23.55-38.36 0-45.6zM352.79 315.09c-28.53 8.76-52.84 3.92-65.59 0l-145.02-44.55L128 384c0 35.35 85.96 64 192 64s192-28.65 192-64l-14.18-113.47-145.03 44.56z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.degree'|trans }}</span>
						</a>
					</li>
				{% endif %}
				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_SCHOOL_NAME')) %}
					<li>
						<a href="{{ path('school_validate') }}">
							<svg
								xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512">
								<!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
								<path class="pf" d="M319.4 320.6L224 416l-95.4-95.4C57.1 323.7 0 382.2 0 454.4v9.6c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-9.6c0-72.2-57.1-130.7-128.6-133.8zM13.6 79.8l6.4 1.5v58.4c-7 4.2-12 11.5-12 20.3 0 8.4 4.6 15.4 11.1 19.7L3.5 242c-1.7 6.9 2.1 14 7.6 14h41.8c5.5 0 9.3-7.1 7.6-14l-15.6-62.3C51.4 175.4 56 168.4 56 160c0-8.8-5-16.1-12-20.3V87.1l66 15.9c-8.6 17.2-14 36.4-14 57 0 70.7 57.3 128 128 128s128-57.3 128-128c0-20.6-5.3-39.8-14-57l96.3-23.2c18.2-4.4 18.2-27.1 0-31.5l-190.4-46c-13-3.1-26.7-3.1-39.7 0L13.6 48.2c-18.1 4.4-18.1 27.2 0 31.6z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.trainee'|trans }}</span>
						</a>
					</li>
				{% endif %}

				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_COMPAGNY_NAME')) %}
					<li>
						<a href="{{ path('compagny_internship_index') }}">
							<svg
								xmlns="http://www.w3.org/2000/svg" viewbox="0 0 544 512">
								<!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
								<path class="pf" d="M0 479.98L99.92 512l35.45-35.45-67.04-67.04L0 479.98zm124.61-240.01a36.592 36.592 0 0 0-10.79 38.1l13.05 42.83-50.93 50.94 96.23 96.23 50.86-50.86 42.74 13.08c13.73 4.2 28.65-.01 38.15-10.78l35.55-41.64-173.34-173.34-41.52 35.44zm403.31-160.7l-63.2-63.2c-20.49-20.49-53.38-21.52-75.12-2.35L190.55 183.68l169.77 169.78L530.27 154.4c19.18-21.74 18.15-54.63-2.35-75.13z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.internship'|trans }}</span>
						</a>
					</li>
				{% endif %}
				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_COMPAGNY_NAME')) %}
					<li>
						<a href="{{ path('compagny_trainee') }}">
							<svg
								xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512">
								<!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
								<path class="pf" d="M319.4 320.6L224 416l-95.4-95.4C57.1 323.7 0 382.2 0 454.4v9.6c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-9.6c0-72.2-57.1-130.7-128.6-133.8zM13.6 79.8l6.4 1.5v58.4c-7 4.2-12 11.5-12 20.3 0 8.4 4.6 15.4 11.1 19.7L3.5 242c-1.7 6.9 2.1 14 7.6 14h41.8c5.5 0 9.3-7.1 7.6-14l-15.6-62.3C51.4 175.4 56 168.4 56 160c0-8.8-5-16.1-12-20.3V87.1l66 15.9c-8.6 17.2-14 36.4-14 57 0 70.7 57.3 128 128 128s128-57.3 128-128c0-20.6-5.3-39.8-14-57l96.3-23.2c18.2-4.4 18.2-27.1 0-31.5l-190.4-46c-13-3.1-26.7-3.1-39.7 0L13.6 48.2c-18.1 4.4-18.1 27.2 0 31.6z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.trainee'|trans }}</span>
						</a>
					</li>
				{% endif %}
				{% if is_granted(constant('App\\Constants\\Permissions::ROLE_COMPAGNY_NAME')) and not Anonymisation or is_granted(constant('App\\Constants\\Permissions::ROLE_TRAINEE_NAME')) and not settings.isAnonymisationEnabled %}
					<li>
						<a href="{{ path('account_messaging') }}">
							<svg
								xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
								<!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
								<path class="pf" d="M256 32C114.6 32 0 125.1 0 240c0 49.6 21.4 95 57 130.7C44.5 421.1 2.7 466 2.2 466.5c-2.2 2.3-2.8 5.7-1.5 8.7S4.8 480 8 480c66.3 0 116-31.8 140.6-51.4 32.7 12.3 69 19.4 107.4 19.4 141.4 0 256-93.1 256-208S397.4 32 256 32z"/>
							</svg>
							<span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.messaging'|trans }}</span>
						</a>
					</li>
				{% endif %}
				<li>
					<dropdown>
						<input id="toggle2" type="checkbox"/>

						<label for="toggle2" class="animate">
							<svg class="u_ sy ov" viewbox="0 0 24 24">
								<path class="pf " :class="page.startsWith('settings-') &amp;&amp; 'text-indigo-500'" d="M19.714 14.7l-7.007 7.007-1.414-1.414 7.007-7.007c-.195-.4-.298-.84-.3-1.286a3 3 0 113 3 2.969 2.969 0 01-1.286-.3z"></path>
								<path class="pf" :class="page.startsWith('settings-') &amp;&amp; 'text-indigo-300'" d="M10.714 18.3c.4-.195.84-.298 1.286-.3a3 3 0 11-3 3c.002-.446.105-.885.3-1.286l-6.007-6.007 1.414-1.414 6.007 6.007z"></path>
								<path class="pf " :class="page.startsWith('settings-') &amp;&amp; 'text-indigo-500'" d="M5.7 10.714c.195.4.298.84.3 1.286a3 3 0 11-3-3c.446.002.885.105 1.286.3l7.007-7.007 1.414 1.414L5.7 10.714z"></path>
								<path class="pf " :class="page.startsWith('settings-') &amp;&amp; 'text-indigo-300'" d="M19.707 9.292a3.012 3.012 0 00-1.415 1.415L13.286 5.7c-.4.195-.84.298-1.286.3a3 3 0 113-3 2.969 2.969 0 01-.3 1.286l5.007 5.006z"></path>
							</svg>
							{{ 'navigation.settings'|trans }}
							<i class="animate fas fa-sort-down"></i>
							<i class="animate fas fa-sort-up"></i>
						</label>
						<ul>
							<li class="animate">
								{% if is_granted(constant('App\\Constants\\Permissions::ROLE_COMPAGNY_NAME')) %}
									<a href="{{ path('compagny_edit') }}#myaccount" data-target="myaccount" class="settings-sidebar-item">{{ 'navigation.account'|trans }}</a>
								{% elseif  is_granted(constant('App\\Constants\\Permissions::ROLE_SCHOOL_NAME')) %}
									<a href="{{ path('school_edit') }}#myaccount" data-target="myaccount" class="settings-sidebar-item">{{ 'navigation.account'|trans }}</a>
								{% elseif  is_granted(constant('App\\Constants\\Permissions::ROLE_TRAINEE_NAME')) %}
									<a href="{{ path('account_settings') }}#myaccount" data-target="myaccount" class="settings-sidebar-item">{{ 'navigation.account'|trans }}</a>
								{% endif %}
							</li>
						</ul>
					</dropdown>
				</li>


			</ul>
		</div>

		<div class="content">
			<div class="row navbar">
				<div class="col-6">
					<i class="fas fa-bars navbar-toogle"></i>
				</div>
				<div class="col-6">
					<a href="{{ path('app_logout') }}">{{ 'navigation.logout'|trans }}
						{% if app.user %}
							{% if is_granted(constant('App\\Constants\\Permissions::ROLE_COMPAGNY_NAME')) %}
								(
								{{ app.user.name }}
								)
							{% elseif  is_granted(constant('App\\Constants\\Permissions::ROLE_SCHOOL_NAME')) %}
								(
								{{ app.user.name }}
								)
							{% elseif  is_granted(constant('App\\Constants\\Permissions::ROLE_TRAINEE_NAME')) %}
								(
								{{ app.user.lastname }}
								{{ app.user.firstname }}
								)
							{% endif %}
						{% endif %}
						<i class="fas fa-sign-out-alt"></i>
					</a>
				</div>
			</div>
			<div class="content-body">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>

{% endblock %}

templates/admin.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('account') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('account') }}
{% endblock %}

{% block body %}

    <div class="container-fluid movable">

        <div class="sidebar">
            <div class="sidebar-logo">
                <a href="{{ path('admin') }}">
                    <i class="animate fas fa-arrow-left navbar-toogle"></i>
                </a>
                <a href="{{ path('app_home') }} ">
                    <img src="{{ asset('images/pf.png') }}" alt="Logo">
                </a>
            </div>

            <ul>

                <li>
                    <a href="{{ path('account') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path class="pf"
                                  d="M11.5 280.6l192 160c20.6 17.2 52.5 2.8 52.5-24.6V96c0-27.4-31.9-41.8-52.5-24.6l-192 160c-15.3 12.8-15.3 36.4 0 49.2zm256 0l192 160c20.6 17.2 52.5 2.8 52.5-24.6V96c0-27.4-31.9-41.8-52.5-24.6l-192 160c-15.3 12.8-15.3 36.4 0 49.2z"/>
                        </svg>
                        <span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.backToAccount'|trans }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ path('admin') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                            <!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
                            <path class="pf"
                                  d="M336 64h-80c0-35.3-28.7-64-64-64s-64 28.7-64 64H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48zM192 40c13.3 0 24 10.7 24 24s-10.7 24-24 24-24-10.7-24-24 10.7-24 24-24zm121.2 231.8l-143 141.8c-4.7 4.7-12.3 4.6-17-.1l-82.6-83.3c-4.7-4.7-4.6-12.3.1-17L99.1 285c4.7-4.7 12.3-4.6 17 .1l46 46.4 106-105.2c4.7-4.7 12.3-4.6 17 .1l28.2 28.4c4.7 4.8 4.6 12.3-.1 17z"/>
                        </svg>
                        <span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.dashboard'|trans }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ path('admin_validation') }}">
                        <svg class="a_ ow ug" viewbox="0 0 24 24">
                            <path class="pf ml" :class="page === 'dashboard' &amp;&amp; '!text-indigo-500'"
                                  d="M12 0C5.383 0 0 5.383 0 12s5.383 12 12 12 12-5.383 12-12S18.617 0 12 0z"></path>
                            <path class="pf ma" :class="page === 'dashboard' &amp;&amp; 'text-indigo-600'"
                                  d="M12 3c-4.963 0-9 4.037-9 9s4.037 9 9 9 9-4.037 9-9-4.037-9-9-9z"></path>
                            <path class="pf ml" :class="page === 'dashboard' &amp;&amp; 'text-indigo-200'"
                                  d="M12 15c-1.654 0-3-1.346-3-3 0-.462.113-.894.3-1.285L6 6l4.714 3.301A2.973 2.973 0 0112 9c1.654 0 3 1.346 3 3s-1.346 3-3 3z"></path>
                        </svg>
                        <span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.validation'|trans }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ path('admin_reporting') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <!--! Font Awesome Pro 6.1.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
                            <path class="pf" d="M64 496C64 504.8 56.75 512 48 512h-32C7.25 512 0 504.8 0 496V32c0-17.75 14.25-32 32-32s32 14.25 32 32V496zM476.3 0c-6.365 0-13.01 1.35-19.34 4.233c-45.69 20.86-79.56 27.94-107.8 27.94c-59.96 0-94.81-31.86-163.9-31.87C160.9 .3055 131.6 4.867 96 15.75v350.5c32-9.984 59.87-14.1 84.85-14.1c73.63 0 124.9 31.78 198.6 31.78c31.91 0 68.02-5.971 111.1-23.09C504.1 355.9 512 344.4 512 332.1V30.73C512 11.1 495.3 0 476.3 0z"/>
                        </svg>
                        <span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.reporting'|trans }}</span>
                    </a>
                </li>

                <li>
                    <a href="{{ path('admin_settings') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) -->
                            <path class="pf"
                                  d="M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.8 110c-17.9-15.4-38.5-27.3-60.8-35.1V25.8c0-5.6-3.9-10.5-9.4-11.7-36.7-8.2-74.3-7.8-109.2 0-5.5 1.2-9.4 6.1-9.4 11.7V75c-22.2 7.9-42.8 19.8-60.8 35.1L88.7 85.5c-4.9-2.8-11-1.9-14.8 2.3-24.7 26.7-43.6 58.9-54.7 94.6-1.7 5.4.6 11.2 5.5 14L67.3 221c-4.3 23.2-4.3 47 0 70.2l-42.6 24.6c-4.9 2.8-7.1 8.6-5.5 14 11.1 35.6 30 67.8 54.7 94.6 3.8 4.1 10 5.1 14.8 2.3l42.6-24.6c17.9 15.4 38.5 27.3 60.8 35.1v49.2c0 5.6 3.9 10.5 9.4 11.7 36.7 8.2 74.3 7.8 109.2 0 5.5-1.2 9.4-6.1 9.4-11.7v-49.2c22.2-7.9 42.8-19.8 60.8-35.1l42.6 24.6c4.9 2.8 11 1.9 14.8-2.3 24.7-26.7 43.6-58.9 54.7-94.6 1.5-5.5-.7-11.3-5.6-14.1zM256 336c-44.1 0-80-35.9-80-80s35.9-80 80-80 80 35.9 80 80-35.9 80-80 80z"/>
                        </svg>
                        <span class="text-sm me ml-3 jo jh 2xl:opacity--100 gj">{{ 'navigation.settings'|trans }}</span>
                    </a>
                </li>
            </ul>
        </div>

        <div class="content">
            <div class="row navbar">
                <div class="col-6">
                    <i class="fas fa-bars navbar-toogle"></i>
                </div>
                <div class="col-6">
                    <a href="{{ path('app_logout') }}">
                        {{ 'navigation.logout'|trans }}
                        ( {{ app.user.name }} ) 
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </div>
            </div>
            <div class="content-body">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}PerfectMatch{% endblock %}
    </title>
    <link
            rel="icon"
            href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% set Anonymisation = settings.isAnonymisationEnabled %}
</head>
<body>
{% block body %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/40cde147ab.js"></script>

{{ encore_entry_script_tags('app') }}

{% block javascripts %}{% endblock %}

{% block modal %}{% endblock %}
</body>
</html>

templates/credentials.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link type="text/css" rel="stylesheet" href="{{ asset('bundles/craueformflow/css/buttons.css') }}"/>
    {{ encore_entry_link_tags('credentials') }}
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('credentials') }}
{% endblock %}

{% block body %}
<div class="loginWrapper container-fluid row m-0">
    <div class="imgWrapper col-md-5">
        <div></div>
        <img src="{{ asset('/images/bck.webp') }}" class="img-fluid" alt="european background">
    </div>
    <div class="row formWrapper col-md-7 m-0">

        {% if split %}
        <div class="col-sm-6 mb-5 d-flex justify-content-center">
            <div class="d-flex justify-content-center align-items-center">
                <a href="{{ path('app_home') }}"><img src="{{ asset('images/pf.png') }}" alt="logo"></a>
            </div>
        </div>
        <div class="col-sm-6">
            {% else %}
            <div>
                <a href="{{ path('app_home') }}"><img class="reduce" src="{{ asset('images/pf.png') }}" alt="logo"></a>
                <br/>

                {% endif %}
                {% if  app.request.get('_route') != "app_login"%}
                    <div class="form-action mb-5">
                        <a href="{{ path('app_home') }}" class="active">{{ 'register.goback'|trans }}</a>
                        |
                        <a href="{{ path('app_login') }}" class="active">{{ 'register.alreadyhaveaccount'|trans }}</a>
                    </div>
                {% else %}
                    <div class="form-action mb-1">
                        <a href="{{ path('app_home') }}" class="active">{{ 'register.goback'|trans }}</a>
                    </div>
                {% endif %}
                {% block form %}{% endblock %}
            </div>


            {# <div class="row login-infos mt-5 mx-0">
					<a class="mb-5" href="">LavoriAmo - Easy online</a>

					<p>
						<strong>JOB SPEED DATE 04 NOVEMBER 2021</strong>
						Web platform for job interviews
					</p>

					<p>
						<strong>Meet</strong>
						companies,
						<strong>apply</strong>
						for job offers,
						<strong>participate</strong>
						in company and orientation workshops!
					</p>
				</div> #}
        </div>
    </div>
</div>
{% endblock %}